//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:25:55 AM CEST 
//


package osh.configuration.oc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import osh.configuration.system.ConfigurationParameter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="globalOcUuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="globalControllerClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="globalControllerParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="globalObserverClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="globalObserverParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="optimizationMainRandomSeed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gaConfiguration" type="{http://osh/Configuration/ControllerBox}GAConfiguration"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalOcUuid",
    "globalControllerClass",
    "globalControllerParameters",
    "globalObserverClass",
    "globalObserverParameters",
    "optimizationMainRandomSeed",
    "gaConfiguration"
})
@XmlRootElement(name = "OCConfiguration")
public class OCConfiguration {

    @XmlElement(required = true)
    protected String globalOcUuid;
    @XmlElement(required = true)
    protected String globalControllerClass;
    protected List<ConfigurationParameter> globalControllerParameters;
    @XmlElement(required = true)
    protected String globalObserverClass;
    protected List<ConfigurationParameter> globalObserverParameters;
    @XmlElement(required = true)
    protected String optimizationMainRandomSeed;
    @XmlElement(required = true)
    protected GAConfiguration gaConfiguration;

    /**
     * Gets the value of the globalOcUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalOcUuid() {
        return globalOcUuid;
    }

    /**
     * Sets the value of the globalOcUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalOcUuid(String value) {
        this.globalOcUuid = value;
    }

    /**
     * Gets the value of the globalControllerClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalControllerClass() {
        return globalControllerClass;
    }

    /**
     * Sets the value of the globalControllerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalControllerClass(String value) {
        this.globalControllerClass = value;
    }

    /**
     * Gets the value of the globalControllerParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalControllerParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlobalControllerParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getGlobalControllerParameters() {
        if (globalControllerParameters == null) {
            globalControllerParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.globalControllerParameters;
    }

    /**
     * Gets the value of the globalObserverClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalObserverClass() {
        return globalObserverClass;
    }

    /**
     * Sets the value of the globalObserverClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalObserverClass(String value) {
        this.globalObserverClass = value;
    }

    /**
     * Gets the value of the globalObserverParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalObserverParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlobalObserverParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getGlobalObserverParameters() {
        if (globalObserverParameters == null) {
            globalObserverParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.globalObserverParameters;
    }

    /**
     * Gets the value of the optimizationMainRandomSeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptimizationMainRandomSeed() {
        return optimizationMainRandomSeed;
    }

    /**
     * Sets the value of the optimizationMainRandomSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptimizationMainRandomSeed(String value) {
        this.optimizationMainRandomSeed = value;
    }

    /**
     * Gets the value of the gaConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link GAConfiguration }
     *     
     */
    public GAConfiguration getGaConfiguration() {
        return gaConfiguration;
    }

    /**
     * Sets the value of the gaConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAConfiguration }
     *     
     */
    public void setGaConfiguration(GAConfiguration value) {
        this.gaConfiguration = value;
    }

}
