//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:25:55 AM CEST 
//


package osh.configuration.oc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import osh.configuration.system.ConfigurationParameter;


/**
 * <p>Java class for StoppingRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoppingRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stoppingRuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoppingRule", propOrder = {
    "stoppingRuleName",
    "ruleParameters"
})
public class StoppingRule {

    @XmlElement(required = true)
    protected String stoppingRuleName;
    protected List<ConfigurationParameter> ruleParameters;

    /**
     * Gets the value of the stoppingRuleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoppingRuleName() {
        return stoppingRuleName;
    }

    /**
     * Sets the value of the stoppingRuleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoppingRuleName(String value) {
        this.stoppingRuleName = value;
    }

    /**
     * Gets the value of the ruleParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getRuleParameters() {
        if (ruleParameters == null) {
            ruleParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.ruleParameters;
    }

}
