//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:20:23 AM CEST 
//


package osh.configuration.eal;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import osh.configuration.system.ConfigurationParameter;


/**
 * <p>Java class for AssignedLocalOCUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssignedLocalOCUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localControllerClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localObserverClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localObserverParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="localControllerParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssignedLocalOCUnit", propOrder = {
    "unitDescription",
    "localControllerClassName",
    "localObserverClassName",
    "localObserverParameters",
    "localControllerParameters"
})
public class AssignedLocalOCUnit {

    @XmlElement(required = true)
    protected String unitDescription;
    @XmlElement(required = true)
    protected String localControllerClassName;
    @XmlElement(required = true)
    protected String localObserverClassName;
    protected List<ConfigurationParameter> localObserverParameters;
    protected List<ConfigurationParameter> localControllerParameters;

    /**
     * Gets the value of the unitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitDescription() {
        return unitDescription;
    }

    /**
     * Sets the value of the unitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitDescription(String value) {
        this.unitDescription = value;
    }

    /**
     * Gets the value of the localControllerClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalControllerClassName() {
        return localControllerClassName;
    }

    /**
     * Sets the value of the localControllerClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalControllerClassName(String value) {
        this.localControllerClassName = value;
    }

    /**
     * Gets the value of the localObserverClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalObserverClassName() {
        return localObserverClassName;
    }

    /**
     * Sets the value of the localObserverClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalObserverClassName(String value) {
        this.localObserverClassName = value;
    }

    /**
     * Gets the value of the localObserverParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localObserverParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalObserverParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getLocalObserverParameters() {
        if (localObserverParameters == null) {
            localObserverParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.localObserverParameters;
    }

    /**
     * Gets the value of the localControllerParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localControllerParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalControllerParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getLocalControllerParameters() {
        if (localControllerParameters == null) {
            localControllerParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.localControllerParameters;
    }

}
