//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:20:23 AM CEST 
//


package osh.configuration.eal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assignedDevices" type="{http://osh/Configuration/System}AssignedDevice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="assignedBusDevices" type="{http://osh/Configuration/System}AssignedBusDevice" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assignedDevices",
    "assignedBusDevices"
})
@XmlRootElement(name = "EALConfiguration")
public class EALConfiguration {

    protected List<AssignedDevice> assignedDevices;
    protected List<AssignedBusDevice> assignedBusDevices;

    /**
     * Gets the value of the assignedDevices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedDevices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedDevice }
     * 
     * 
     */
    public List<AssignedDevice> getAssignedDevices() {
        if (assignedDevices == null) {
            assignedDevices = new ArrayList<AssignedDevice>();
        }
        return this.assignedDevices;
    }

    /**
     * Gets the value of the assignedBusDevices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedBusDevices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedBusDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedBusDevice }
     * 
     * 
     */
    public List<AssignedBusDevice> getAssignedBusDevices() {
        if (assignedBusDevices == null) {
            assignedBusDevices = new ArrayList<AssignedBusDevice>();
        }
        return this.assignedBusDevices;
    }

}
