//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:20:44 AM CEST 
//


package osh.configuration.system;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeviceTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HVAC"/>
 *     &lt;enumeration value="COMBINATIONAPPARATUS"/>
 *     &lt;enumeration value="AIRCONDITION"/>
 *     &lt;enumeration value="FANHEATER"/>
 *     &lt;enumeration value="DISHWASHER"/>
 *     &lt;enumeration value="DRYER"/>
 *     &lt;enumeration value="WASHERDRYER"/>
 *     &lt;enumeration value="WASHINGMACHINE"/>
 *     &lt;enumeration value="ELECTRICOVEN"/>
 *     &lt;enumeration value="ELECTRICSTOVE"/>
 *     &lt;enumeration value="ELECTRICCOOKTOP"/>
 *     &lt;enumeration value="INDUCTIONCOOKTOP"/>
 *     &lt;enumeration value="GASOVEN"/>
 *     &lt;enumeration value="GASSTOVE"/>
 *     &lt;enumeration value="GASCOOKTOP"/>
 *     &lt;enumeration value="COOKERHOOD"/>
 *     &lt;enumeration value="MICROWAVE"/>
 *     &lt;enumeration value="STEAMER"/>
 *     &lt;enumeration value="BREADMAKER"/>
 *     &lt;enumeration value="COFFEESYSTEM"/>
 *     &lt;enumeration value="COFFEEMAKER"/>
 *     &lt;enumeration value="FREEZERREFRIGERATOR"/>
 *     &lt;enumeration value="FREEZER"/>
 *     &lt;enumeration value="REFRIGERATOR"/>
 *     &lt;enumeration value="WINECOOLER"/>
 *     &lt;enumeration value="ELECTRICWATERBOILER"/>
 *     &lt;enumeration value="WATERHEATERINSTANTANEOUS"/>
 *     &lt;enumeration value="WATERHEATERSTORAGE"/>
 *     &lt;enumeration value="LUMINAIRE"/>
 *     &lt;enumeration value="ECAR"/>
 *     &lt;enumeration value="EBIKE"/>
 *     &lt;enumeration value="SEGWAY"/>
 *     &lt;enumeration value="SMARTMETER"/>
 *     &lt;enumeration value="TEMPERATURESENSOR"/>
 *     &lt;enumeration value="GASSENSOR"/>
 *     &lt;enumeration value="SMOKESENSOR"/>
 *     &lt;enumeration value="MOTIONSENSOR"/>
 *     &lt;enumeration value="CONTACTSENSOR"/>
 *     &lt;enumeration value="METERPLUG"/>
 *     &lt;enumeration value="SWITCHPLUG"/>
 *     &lt;enumeration value="METERSWITCHPLUG"/>
 *     &lt;enumeration value="VIRTUALSWITCH"/>
 *     &lt;enumeration value="CHPPLANT"/>
 *     &lt;enumeration value="PVSYSTEM"/>
 *     &lt;enumeration value="HEATPUMP"/>
 *     &lt;enumeration value="IR"/>
 *     &lt;enumeration value="BASELOAD"/>
 *     &lt;enumeration value="HOUSEHOLD"/>
 *     &lt;enumeration value="HOTWATERSTORAGE"/>
 *     &lt;enumeration value="COLDWATERSTORAGE"/>
 *     &lt;enumeration value="ADSORPTIONCHILLER"/>
 *     &lt;enumeration value="SPACECOOLING"/>
 *     &lt;enumeration value="SPACEHEATING"/>
 *     &lt;enumeration value="DOMESTICHOTWATER"/>
 *     &lt;enumeration value="INSERTHEATINGELEMENT"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="BATTERYSTORAGE"/>
 *     &lt;enumeration value="GASHEATING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeviceTypes")
@XmlEnum
public enum DeviceTypes {

    HVAC,
    COMBINATIONAPPARATUS,
    AIRCONDITION,
    FANHEATER,
    DISHWASHER,
    DRYER,
    WASHERDRYER,
    WASHINGMACHINE,
    ELECTRICOVEN,
    ELECTRICSTOVE,
    ELECTRICCOOKTOP,
    INDUCTIONCOOKTOP,
    GASOVEN,
    GASSTOVE,
    GASCOOKTOP,
    COOKERHOOD,
    MICROWAVE,
    STEAMER,
    BREADMAKER,
    COFFEESYSTEM,
    COFFEEMAKER,
    FREEZERREFRIGERATOR,
    FREEZER,
    REFRIGERATOR,
    WINECOOLER,
    ELECTRICWATERBOILER,
    WATERHEATERINSTANTANEOUS,
    WATERHEATERSTORAGE,
    LUMINAIRE,
    ECAR,
    EBIKE,
    SEGWAY,
    SMARTMETER,
    TEMPERATURESENSOR,
    GASSENSOR,
    SMOKESENSOR,
    MOTIONSENSOR,
    CONTACTSENSOR,
    METERPLUG,
    SWITCHPLUG,
    METERSWITCHPLUG,
    VIRTUALSWITCH,
    CHPPLANT,
    PVSYSTEM,
    HEATPUMP,
    IR,
    BASELOAD,
    HOUSEHOLD,
    HOTWATERSTORAGE,
    COLDWATERSTORAGE,
    INSERTHEATINGELEMENT,
    ADSORPTIONCHILLER,
    SPACECOOLING,
    SPACEHEATING,
    DOMESTICHOTWATER,
    GASHEATING,
    BATTERYSTORAGE,
    OTHER;

    public String value() {
        return name();
    }

    public static DeviceTypes fromValue(String v) {
        return valueOf(v);
    }

}
