//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:20:44 AM CEST 
//


package osh.configuration.system;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GridConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gridType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gridLayoutSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridConfig", propOrder = {
    "gridType",
    "gridLayoutSource"
})
public class GridConfig {

    @XmlElement(required = true)
    protected String gridType;
    @XmlElement(required = true)
    protected String gridLayoutSource;

    /**
     * Gets the value of the gridType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridType() {
        return gridType;
    }

    /**
     * Sets the value of the gridType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridType(String value) {
        this.gridType = value;
    }

    /**
     * Gets the value of the gridLayoutSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridLayoutSource() {
        return gridLayoutSource;
    }

    /**
     * Sets the value of the gridLayoutSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridLayoutSource(String value) {
        this.gridLayoutSource = value;
    }

}
