//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:20:44 AM CEST 
//


package osh.configuration.system;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="runningType" type="{http://osh/Configuration/System}runningType"/>
 *         &lt;element name="randomSeed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="engineParameters" type="{http://osh/Configuration/System}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="logFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gridConfigurations" type="{http://osh/Configuration/System}GridConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="meterUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hhUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runningType",
    "randomSeed",
    "engineParameters",
    "logFilePath",
    "gridConfigurations",
    "meterUUID",
    "hhUUID"
})
@XmlRootElement(name = "OSHConfiguration")
public class OSHConfiguration {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RunningType runningType;
    @XmlElement(required = true)
    protected String randomSeed;
    protected List<ConfigurationParameter> engineParameters;
    @XmlElement(required = true)
    protected String logFilePath;
    protected List<GridConfig> gridConfigurations;
    @XmlElement(required = true)
    protected String meterUUID;
    @XmlElement(required = true)
    protected String hhUUID;

    /**
     * Gets the value of the runningType property.
     * 
     * @return
     *     possible object is
     *     {@link RunningType }
     *     
     */
    public RunningType getRunningType() {
        return runningType;
    }

    /**
     * Sets the value of the runningType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunningType }
     *     
     */
    public void setRunningType(RunningType value) {
        this.runningType = value;
    }

    /**
     * Gets the value of the randomSeed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRandomSeed() {
        return randomSeed;
    }

    /**
     * Sets the value of the randomSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRandomSeed(String value) {
        this.randomSeed = value;
    }

    /**
     * Gets the value of the engineParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the engineParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEngineParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getEngineParameters() {
        if (engineParameters == null) {
            engineParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.engineParameters;
    }

    /**
     * Gets the value of the logFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFilePath() {
        return logFilePath;
    }

    /**
     * Sets the value of the logFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFilePath(String value) {
        this.logFilePath = value;
    }

    /**
     * Gets the value of the gridConfigurations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridConfigurations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGridConfigurations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GridConfig }
     * 
     * 
     */
    public List<GridConfig> getGridConfigurations() {
        if (gridConfigurations == null) {
            gridConfigurations = new ArrayList<GridConfig>();
        }
        return this.gridConfigurations;
    }

    /**
     * Gets the value of the meterUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterUUID() {
        return meterUUID;
    }

    /**
     * Sets the value of the meterUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterUUID(String value) {
        this.meterUUID = value;
    }

    /**
     * Gets the value of the hhUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHhUUID() {
        return hhUUID;
    }

    /**
     * Sets the value of the hhUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHhUUID(String value) {
        this.hhUUID = value;
    }

}
